id = "naysayer"
name = "Naysayer"
version = "1.0.0"
schema_version = 1
authors = ["Dar Zaccaro <darzaccaro@gmail.com>"]
description = "A color theme for Zed inspired by Jonathan Blow's emacs theme."
repository = "https://github.com/darzaccaro/naysayer-theme"
